import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Box from "@mui/material/Box";
import StoreProvider from "@/redux/provider";
import UserPending from "./_component/Dialog/userPending";
import RootMenu from "./rootMenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Box sx={{ display: "flex" }}>
            <RootMenu />
            {children}
            <UserPending />
          </Box>
        </body>
      </html>
    </StoreProvider>
  );
}
